name: CI
on: [ push]
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd backend
          yarn install
      - name: Build
        run: |
          cd backend
          yarn run tsc index.ts --outDir build
      - name: Zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip .
          working-directory: ./backend/build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle-artifact
          path: ./backend/build/bundle.zip
          retention-days: 1
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-2
          function_name: spotify-playlist-splitter-backend
          zip_file: ./backend/build/bundle.zip