name: CI
on: [ push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build Backend
        run: |
          cd backend
          yarn install
          yarn build
      - name: Install Zip
        uses: montudor/action-zip@v0.1.0
      - name: Zip Backend
        run: zip -qq -r ./bundle.zip .
        working-directory: ./backend/build
#      - name: Debug
#        run: |
#          ls
#          cd backend
#          echo ===BACKEND===
#          ls
#          cd build
#          echo ===BUILD===
#          ls
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: bundle-artifact
#          path: ./backend/build/bundle.zip
#          retention-days: 1
      - name: Deploy Backend
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-2
          function_name: spotify-playlist-splitter-backend
          zip_file: ./backend/build/bundle.zip
      - name: Build Frontend
        run: |
          cd frontend2
          yarn install
          yarn generate
      - name: Deploy Frontend
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend2/dist